version: '3.7'

services:
  flask_gunicorn:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_gunicorn
  
  scheduler:
    restart: always
    build: ./scheduler
    ports:
      - "8080:8080"
    depends_on:
      - flask_gunicorn

volumes:
  static: